### PR TITLE
Sphinx setup for building documentation

### PR DESCRIPTION
**Pull request by andresailer**
This adds the sphinx configuration for RTD to build the documentation. Fixes the dirac os parts of #130 

At the moment I created a folder in the base dir called docs_rtd, but it could also be a subfolder of docs.
Let me know what you prefer.

I had to create an index.rst to get a toctree going, I couldn't just use the README.rst as the basefile.
Also fixed one warning from sphinx and one typo

It looks like this: https://diracos.readthedocs.io/en/latest/index.html

### CODE REVIEW

**Comment by chrisburr** [comment]
> I had to create an index.rst to get a toctree going, I couldn't just use the README.rst as the basefile.

We could remove the table of contents from the README and just link to readthedocs?

**Comment by andresailer** [comment]
Is this what you had in mind? 

If there is no links on github Readme.rst, I can also just merge everything in one folder and move the rst files from `docs` to `docs/source` ?

**Comment by chaen** [comment]
even better :)

**Comment by andresailer** [comment]
moved the files to docs/source.

If this is merged I will change the git location in RTD to diracgrid, and then someone with permissions needs to install the webhook so it gets updated.
I added @chaen and @petricm as maintainers to the diracos.readthedocs.io as well.

**Comment by chaen** [comment]
@petricm can you take care of the webhook please ?

**Comment by petricm** [comment]
I cannot do the webhook, don't have enough karma. @fstagni has to do it.

**Comment by fstagni** [comment]
I think I did.

**Pull request merged**
