### PR TITLE
Add Authlib, PyJWT and dominate and sort list

### LINKED ISSUE #178: Add authlib, pyjwt, dominate
It would be good to add the following packages to pass the [#5149](https://github.com/DIRACGrid/DIRAC/pull/5149) tests:
- authlib <= 0.15.3
- pyjwt <= 1.7.1
- dominate

### PR DESCRIPTION
**Pull request by petricm**
resolves #178 
BEGINRELEASENOTES

NEW: Add python libraries Authlib, PyJWT and dominate

ENDRELEASENOTES

### CODE REVIEW

**Comment by petricm** [comment]
test in https://gitlab.cern.ch/CLICdp/iLCDirac/diracos-test/-/pipelines/2632072

**Review by chrisburr — CHANGES_REQUESTED** [review]
Nobody has yet advocated for Python 2 support in https://github.com/DIRACGrid/DIRACOS/issues/178 so this might not be needed.

**Comment by chaen** [comment]
@TaykYoku I think there is a misunderstanding. We discussed extensively this, particularly at the last BILD, and the conclusion was that there will be no support in python 2 for tokens in DIRAC (see minutes https://indico.cern.ch/event/1048250/). So there is no need for these packages in DIRACOS

**Comment by TaykYoku** [comment]
Yes, u right, Ill fix it

**Pull request closed without merging**
