### PR TITLE
Generate a diracosrc at build time

### PR DESCRIPTION
**Pull request by chaen**
This allows not to run find everytime we want to use DIRAC
I also renamed the tests according to pytest standards

### CODE REVIEW

**Comment by andresailer** [comment]
What about (t)csh ?

**Comment by chaen** [comment]
http://cdn-webimages.wimages.net/050f927763ee122328503a15382c286a098eec-wm.jpg?v=3

**Comment by chaen** [comment]
I suppose we could generate one as well, but I have no idea of tcsh.

**Comment by fstagni** [comment]
I propose to drop the support for (t)csh.

**Comment by chaen** [comment]
I already proposed this 10000 times but I was always told no, so BIG UP !!! :D

**Comment by chaen** [comment]
Following this morning's discussion, I merge that one

**Pull request merged**
