### PR TITLE
Remove cx_Oracle

### PR DESCRIPTION
**Pull request by chaen**
BEGINRELEASENOTES
CHANGE: remove cx_Oracle
ENDRELEASENOTES

### CODE REVIEW

**Comment by petricm** [comment]
What about:
 - tests/integration/test_import.py
 - tests/integration/test_dyn_import.py
 - config/diracos.json -> java-1.7.0-oracle-devel

**Comment by chaen** [comment]
Argh, forgot an option in `git grep` :-)
For java, it is pulled by ARC I believe, so still needs to be here

**Comment by chaen** [comment]
And for dyn_import, it needs to be here as long as `cx_Oracle` is used in some places in DIRAC

**Comment by petricm** [comment]
arhg, sorry what about the 
```
ALLOWED_TO_FAIL = ['cx_Oracle',  # This is used by some extensions and migration script (LFC->DFC)
```
in test_import.py

**Comment by chaen** [comment]
.... done :)

**Pull request merged**
